### ISSUE TITLE
Change naming in the API doc

### ISSUE THREAD

**Issue by Adafede** [lotusnprod/lotus-search#58]
```
references:
    ids: ...
    references: ...
structures:
    ids: ...
    structures: ...
taxa:
    ids: ...
    taxa: ...
```

seems a bit confusing, what would you think of 

```
references:
    ids: ...
    metadata: ...
structures:
    ids: ...
    metadata: ...
taxa:
    ids: ...
    metadata: ...
```

@bjonnh-work? (see 8a1ed062d4b9c814969e16152259941de5d7bdc2 for more context)
